services:
  db:
    image: mysql:8.4
    container_name: promptcrafter-mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Use only the app user; omit root entirely.
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  web:
    build:
      context: .
      target: prod
      args:
        NEXT_BASE_PATH: ${NEXT_BASE_PATH:-}
    container_name: promptcrafter-web
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      HOSTNAME: 0.0.0.0
      PORT: ${PORT:-3000}
      UNDICI_NO_WASM: ${UNDICI_NO_WASM:-1}
      NODE_OPTIONS: ${NODE_OPTIONS:---max-old-space-size=2048}
      NEXT_BASE_PATH: ${NEXT_BASE_PATH:-}
      NEXT_PUBLIC_BASE_PATH: ${NEXT_BASE_PATH:-}
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_DISCORD_ID: ${AUTH_DISCORD_ID}
      AUTH_DISCORD_SECRET: ${AUTH_DISCORD_SECRET}
      GOOGLE_GEMINI_API_KEY: ${GOOGLE_GEMINI_API_KEY}
      GOOGLE_GEMINI_BASE_URL: ${GOOGLE_GEMINI_BASE_URL}
      ADMIN_EMAILS: ${ADMIN_EMAILS}
      EMAIL_SERVER_HOST: ${EMAIL_SERVER_HOST}
      EMAIL_SERVER_PORT: ${EMAIL_SERVER_PORT}
      EMAIL_SERVER_SECURE: ${EMAIL_SERVER_SECURE}
      EMAIL_SERVER_USER: ${EMAIL_SERVER_USER}
      EMAIL_SERVER_PASSWORD: ${EMAIL_SERVER_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
      PRISMA_SKIP_MIGRATE: ${PRISMA_SKIP_MIGRATE:-true}
    ports:
      - "3000:3000"

volumes:
  db_data:


