services:
  db:
    image: mysql:8.4
    container_name: promptcrafter-chat-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-promptcrafter}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

  web:
    build:
      context: .
      target: dev
    container_name: promptcrafter-chat-web
    restart: unless-stopped
    env_file:
      - .env
    environment:
      HOSTNAME: 0.0.0.0
      PORT: 3000
      SKIP_ENV_VALIDATION: "true"
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
      DATABASE_URL: mysql://${MYSQL_USER:-app}:${MYSQL_PASSWORD:-password}@db:${MYSQL_PORT:-3306}/${MYSQL_DATABASE:-promptcrafter}
      NEXTAUTH_URL: http://localhost:3000
      AUTH_TRUST_HOST: "true"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: >-
      sh -c "npm ci && (npx prisma migrate deploy || npx prisma db push) && npm run dev"

volumes:
  db_data:
